query TournamentsByVideogame($perPage: Int!, $videogameId: ID!) {
  tournaments(query: {
    perPage: $perPage
    page: 1
		filter: {
      videogameIds: [
        $videogameId
      ]
    }
  	}) {
    nodes {
      name
			events( filter: {
				videogameId: [
					$videogameId
				]
				}) {
				id
				name
				competitionTier
			}
    }
  }
}